api_version = "2026-08"

[[extensions]]
name = "theme-extension"
type = "theme"
handle = "theme-extension"
uid = "65b30aae-2fc0-9b48-3e28-e6bf3e801b92f9c75ad7"



    [[extensions.targeting]]
    target = "admin.app.home.render"
    module = "./src/Home.tsx"
    assets = "./assets"